---
# このアプリの名前です。Cookieの名前に使われます。
# サイト内の他のアプリと重ならないようにしなければなりません。
name: ninmae
# このアプリのWeb上の絶対パスです。
# プロトコルやホスト名を付けてはいけません。
path: /auth
# 認証前確認の対象となるアプリを置いている場所です。
# 複数指定できます。
targets:
  - /var/www/html/app
# 信頼できるIPアドレスとドメインです。ドメインはサブドメインを含みます。
trusted:
  ip:
    - "127.0.0.0/8"
    - "169.254.0.0/16"
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "10.0.0.0/8"
    - "::1"
    - "fe80::/10"
    - "fd00::/8"
  domain:
    - ".jp"
# 不審なIPアドレスです。
suspicious:
  ip: []
  domain: []
# 逆引きを行うかどうかです。
reverse_ip: true
# 確認完了後に次に確認を行うまでの時間です。
expire_time:
  truted_ip: null # 常に信頼
  suspicious_ip: -1 # 不可
  trusted_domain: 2592000 # 1 month
  suspicious_domain: -1 # 不可
  other_domain: 86400 # 1 day
  unknown_ip: 3600 # 1 hour
secret:
  # 使用できる文字は 0-9 A-Z a-z + / = - _ です。
  # ランダムバイトをBase64またはURLSAFEなBase64してください。
  # 文字列は10文字以上でなければなりません。
  # SecureRandom.urlsafe_base64(20)
  session: null
  # 使用できる文字は印字可能なASCII(空白含む)です。
  # パターンは256bit分しか意味を持ちません。
  # 40.times.map((0x20 + SecureRandom.random_number(0x7e - 0x20 + 1)).char).join
  auth: null
# 問題集があるディレクトリです。このファイルからの相対パスです。
problems_dir: './problems'
